services:
  - type: web
    name: lg-safelink
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"